[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:3232 app:app"
restartPolicyType = "ON_FAILURE"

[variables]
PORT = "3232" 